# Generated by Django 2.1.7 on 2019-07-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_sale', '0003_auto_20190707_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberID', models.AutoField(primary_key=True, serialize=False)),
                ('memberName', models.CharField(max_length=50)),
                ('memberGender', models.CharField(max_length=5)),
                ('memberPhone', models.IntegerField(null=True)),
                ('memberEmail', models.CharField(max_length=20)),
                ('memberAddr', models.CharField(max_length=20)),
                ('memberJoinTime', models.DateTimeField(null=True)),
                ('memberStatus', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
