# Generated by Django 2.1.7 on 2019-07-17 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_sale', '0005_auto_20190717_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberJoinTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
